class AppLocalizations {
  static const Map<String, Map<String, String>> _translations = {
    'fr': {
      'welcome': 'Bienvenue sur',
      'home': 'Accueil',
      'exams': 'Examens',
      'rooms': 'Salles',
      'calendar': 'Calendrier',
      'profile': 'Profil',
      'upcoming_exams': 'Prochains Examens',
      'ai_assistant': 'Guide', 
      'settings': 'Paramètres',
      'personal_info': 'Informations Personnelles',
      'privacy': 'Confidentialité',
      'logout': 'Se déconnecter',
      'dark_mode': 'Mode Sombre',
      'language': 'Langue',
      'all': 'Tous',
      'upcoming': 'À venir',
      'history': 'Historique',
      'add_exam': 'Ajouter un Examen',
      'add_revision': 'Révision',
      'new_room': 'Nouvelle Salle',
      'search': 'Rechercher une matière, salle, prof...',
      'no_results': 'Aucun résultat',
      'try_filters': 'Essayez de modifier vos filtres.',
      'contact_school': 'Contacter la scolarité',
      'contact_school_desc': 'Absence, retard, documents...',
      'level': 'Niveau',
      'branch': 'Filière',
      'student_id': 'ID Étudiant',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'send': 'Envoyer',
      'message': 'Message',
      'subject': 'Objet',
      'reason_absence': 'Absence',
      'reason_delay': 'Retard',
      'reason_other': 'Autre',
      'ask_question': 'Posez une question...',
    },
    'en': {
      'welcome': 'Welcome to',
      'home': 'Home',
      'exams': 'Exams',
      'rooms': 'Rooms',
      'calendar': 'Calendar',
      'profile': 'Profile',
      'upcoming_exams': 'Upcoming Exams',
      'ai_assistant': 'Guide',
      'settings': 'Settings',
      'personal_info': 'Personal Information',
      'privacy': 'Privacy',
      'logout': 'Logout',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'all': 'All',
      'upcoming': 'Upcoming',
      'history': 'History',
      'add_exam': 'Add Exam',
      'add_revision': 'Revision',
      'new_room': 'New Room',
      'search': 'Search subject, room, teacher...',
      'no_results': 'No results',
      'try_filters': 'Try modifying your filters.',
      'contact_school': 'Contact Administration',
      'contact_school_desc': 'Absence, delay, documents...',
      'level': 'Level',
      'branch': 'Branch',
      'student_id': 'Student ID',
      'save': 'Save',
      'cancel': 'Cancel',
      'send': 'Send',
      'message': 'Message',
      'subject': 'Subject',
      'reason_absence': 'Absence',
      'reason_delay': 'Delay',
      'reason_other': 'Other',
      'ask_question': 'Ask a question...',
    },
  };

  static String get(String key, String langCode) {
    return _translations[langCode]?[key] ?? key;
  }
}
